### ISSUE TITLE
Connectivity issues from GCP

### ISSUE THREAD

**Issue by byronmccollum** [repology/repology-rs#143]
We run Renovate from a GitLab pipeline, on a runner residing in GCP. Since December 11th, Renovate has been unable to connect to Repology. The connection just hangs, and eventually ends up timing out. Are you aware of any network changes (routing / firewall) that might be causing this? I am able to successfully connect from other sources.

```
                                                   My traceroute  [v0.94]
large-canary (10.120.252.2) -> repology.org                                                        2024-12-18T16:29:22+0000
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                                                                   Packets               Pings
 Host                                                                            Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. (waiting for reply)
 2. 87.245.228.32                                                                 0.0%   305   94.7  96.0  94.4 126.0   4.1
 3. 87-245-232-29.retn.net                                                        0.0%   305  129.7 131.2 129.4 166.8   4.4
 4. SPRINTHOST-AS.AS35278.severen.net                                             0.0%   305  130.0 130.2 129.8 178.1   3.2
 5. (waiting for reply)
```

```
 WARN: Repology lookup failed with unexpected error (repository=xxxxx)
       "packageName": "alpine_3_20/py3-gunicorn",
       "err": {
         "name": "TimeoutError",
         "code": "ETIMEDOUT",
         "timings": {
           "start": 1734539103694,
           "socket": 1734539103694,
           "lookup": 1734539103722,
           "error": 1734539163695,
           "phases": {"wait": 0, "dns": 28, "total": 60001}
         },
         "event": "request",
         "message": "Timeout awaiting 'request' for 60000ms",
         "stack": "RequestError: Timeout awaiting 'request' for 60000ms\n    at ClientRequest.<anonymous> (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:970:65)\n    at Object.onceWrapper (node:events:634:26)\n    at ClientRequest.emit (node:events:531:35)\n    at ClientRequest.emit (node:domain:488:12)\n    at ClientRequest.origin.emit (/usr/local/renovate/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)\n    at emitErrorEvent (node:_http_client:101:11)\n    at TLSSocket.socketErrorListener (node:_http_client:504:5)\n    at TLSSocket.emit (node:events:519:28)\n    at TLSSocket.emit (node:domain:488:12)\n    at emitErrorNT (node:internal/streams/destroy:169:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:128:3)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)\n    at Timeout.timeoutHandler [as _onTimeout] (/usr/local/renovate/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/utils/timed-out.js:36:25)\n    at listOnTimeout (node:internal/timers:583:11)\n    at processTimers (node:internal/timers:519:7)",
         "options": {
           "headers": {
             "user-agent": "RenovateBot/38.142.7 (https://github.com/renovatebot/renovate)",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate, br"
           },
           "url": "https://repology.org/tools/project-by?repo=alpine_3_20&name_type=binname&target_page=api_v1_project&noautoresolve=on&name=py3-gunicorn",
           "hostType": "repology",
           "username": "",
           "password": "",
           "method": "GET",
           "http2": false
         }
       }
```

**Comment by AMDmi3** [comment]
Some GCP nets were recently banned for malicious traffic, should be fixed now.

**Comment by byronmccollum** [comment]
> Some GCP nets were recently banned for malicious traffic, should be fixed now.

Just to make sure, by "malicious" do you mean attacks, or just excessive traffic?

**Comment by AMDmi3** [comment]
Spoofed referrers in this case.

**Comment by gnuletik** [comment]
Sorry to bump this issue but we are facing a similar timeout error from AWS:
https://github.com/renovatebot/renovate/discussions/31899

Do you know if similar issues are occurring with AWS ?

Thanks!

**Comment by AMDmi3** [comment]
Source IP address, please

**Comment by gnuletik** [comment]
Thanks for the fast answer @AMDmi3!

It seems that Mend Renovate uses this list of IP addresses:

```json
[
  "35.169.49.18",
  "52.207.155.173",
  "52.0.106.131",
  "34.197.147.244",
  "54.243.119.210",
  "98.82.39.166",
  "107.20.215.6",
  "44.206.201.73",
  "34.239.12.110",
  "52.45.235.219",
  "52.31.29.228",
  "34.239.12.110"
]
```

Source:
```bash
curl https://mend-resources.mend.io/ip.json | jq -r '."developer-platform"'
```

Found here: https://github.com/renovatebot/renovate/discussions/16194#discussioncomment-11589144

However, I'm unable to get the exact IP used in my runs because Mend Renovate doesn't print that.

Thanks!

**Comment by AMDmi3** [comment]
None of these is banned

**Comment by gnuletik** [comment]
Thanks for the feedback @AMDmi3!
I'll see with renovate's author if there's anything on their side:
https://github.com/renovatebot/renovate/discussions/31899#discussioncomment-11751788
